Repository newrelic/newrelic-browser-agent, pull requests merged in 2022-12, with the labels that each got.

#313 Change usage of Buffer to address test-run warning.
  tests/functional/xhr/xhr-dt-header.test.js
  tools/jil/server/asset-server.js
Labels: safe to test

#316 Update jserror bucketing
  CHANGELOG.md
  packages/browser-agent-core/src/features/jserrors/aggregate/index.js
  tests/assets/js-error-column-bucketing.html
  tests/functional/err/assertion-helpers.js
  tests/functional/err/bucketing.test.js
Labels: bug

#331 handle setInfo more gracefully to account for existing jsAttributes
  CHANGELOG.md
  cdn/agent-aggregator/aggregator.js
  tests/assets/custom-attribute-race-condition.html
  tests/assets/pre-existing-custom-attribute-race-condition-precedence.html
  tests/assets/pre-existing-custom-attribute-race-condition.html
  tests/functional/err/attributes.test.js
Labels: bug

#341 update upload NR script to grab from CDN instead of build folder
  .github/workflows/publish-apm.yml
  tools/scripts/upload-to-nr.js
Labels: maintenance

#327 Updating OSS readme header
  README.md
Labels: maintenance

#336 Handle XHR events with undefined hostnames - NR-63240
  CHANGELOG.md
  packages/browser-agent-core/src/common/deny-list/deny-list.js
  tests/assets/xhr-data-url.html
  tests/functional/xhr/xhr-data-url.test.js
Labels: bug, safe to test

#337 Checkout & test future merge when adding "safe to test"
  .github/reusable_wfs/test-setup.yml
  .github/workflows/tests-polyfill.yml
  .github/workflows/tests.yml
Labels: enhancement

#348 PR Build
  .github/workflows/dev-pr.yml
  tools/jil/util/browsers-supported.json
Labels: maintenance

#328 Differentiate babel targets for polyfill and non-polyfill builds (NEWRELIC-5374)
  .gitignore
  cdn/package.json
  cdn/webpack.config.js
  tools/jil/server/asset-server.js
Labels: safe to test, maintenance, standalone

#324 (chore) Update actions from checkout@v2 to @v3 due to Node 12 deprecation
  .github/workflows/publish-apm.yml
  .github/workflows/publish-cdn.yml
  .github/workflows/publish-current.yml
  .github/workflows/publish-dev.yml
  .github/workflows/publish-sudo-polyfills.yml
  .github/workflows/repolinter.yml
  .github/workflows/tests-polyfill.yml
  .github/workflows/tests.yml
Labels: maintenance

#342 Update publish to internal prod envs script
  .github/workflows/publish-internal-prod.yml
  tools/scripts/upload-ab-to-s3.js
Labels: maintenance

#308 BFCache: Pt.1 Redefining unload
  CHANGELOG.md
  packages/browser-agent-core/src/common/config/state/init.js
  packages/browser-agent-core/src/common/event-listener/add-e.js
  packages/browser-agent-core/src/common/event-listener/event-listener-opts.js
  packages/browser-agent-core/src/common/harvest/harvest-scheduler.js
  packages/browser-agent-core/src/common/harvest/harvest.js
  packages/browser-agent-core/src/common/unload/eol.js
  packages/browser-agent-core/src/common/window/load.js
  packages/browser-agent-core/src/common/window/page-visibility.js
  packages/browser-agent-core/src/common/window/visibility.js
  packages/browser-agent-core/src/features/ajax/aggregate/index.js
  packages/browser-agent-core/src/features/metrics/instrument/index.js
  packages/browser-agent-core/src/features/page-view-timing/aggregate/index.js
  packages/browser-agent-core/src/features/page-view-timing/instrument/index.js
  tests/browser/err/zz-error.browser.js
  tests/browser/harvest.browser.js
  tests/functional/api.test.js
  tests/functional/err/attributes.test.js
  tests/functional/final-harvest.test.js
  tests/functional/ins/page-action-submission.test.js
  tests/functional/nav-cookie.test.js
  tests/functional/spa/errors.test.js
  tests/functional/timings.test.js
  tests/functional/xhr/xhr-submission.test.js
  tools/jil/util/browser-matcher.js
Labels: MMF
