Repository newrelic/newrelic-browser-agent, pull requests merged in 2023-03, with the labels that each got.

#399 NEWRELIC-6746 Capture SMs for resources seen, and lazy-load the metrics module AMAP
  CHANGELOG.md
  src/cdn/polyfills.js
  src/features/ajax/aggregate/index.js
  src/features/metrics/aggregate/index.js
  src/features/metrics/constants.js
  src/features/metrics/instrument/index.js
  src/features/metrics/instrument/workers-helper.js
  src/features/session_trace/aggregate/index.js
  src/loaders/api/api.js
  src/loaders/api/apiAsync.js
  tests/assets/resources.html
  tests/browser/api.browser.js
  tests/browser/metrics.browser.js
  tests/browser/obfuscate.browser.js
  tests/functional/err/assertion-helpers.js
  tests/functional/metrics.test.js
  tests/functional/rum/backend-time.test.js
  tests/functional/worker/metrics.test.js
  tools/testing-server/routes/mock-apis.js
Labels: maintenance, standalone, Next Release

#410 NEWRELIC-6934: Re-wrap promise.prototype
  src/common/event-emitter/contextual-ee.js
  src/common/wrap/wrap-fetch.js
  src/common/wrap/wrap-promise.js
  src/features/utils/instrument-base.js
  src/loaders/agent.js
  tests/assets/promise-instanceof.html
  tests/browser/contextual-ee.browser.js
  tests/browser/spa/fetch-body-propagation.browser.js
  tests/browser/spa/fetch-rejections.browser.js
  tests/browser/spa/single-fetch.browser.js
  tests/functional/spa/basic.test.js
Labels: bug, Next Release

#426 NR-93365: Adding safety around interaction node cancelling
  CHANGELOG.md
  jest.config.js
  src/features/spa/aggregate/interaction-node.js
  src/features/spa/aggregate/interaction-node.test.js
  tools/jil/util/browsers-supported.json
Labels: bug, safe to test, Next Release

#427 Collate all SM to page EoL NR-94597
  CHANGELOG.md
  VERSION
  src/common/config/state/init.js
  src/common/harvest/harvest-scheduler.js
  src/features/jserrors/aggregate/index.js
  src/features/metrics/aggregate/index.js
  src/features/page_action/aggregate/index.js
  src/features/spa/aggregate/index.js
  tests/functional/api.test.js
  tests/functional/disable-harvest.test.js
  tests/functional/framework-detection.test.js
  tests/functional/metrics.test.js
  tests/functional/worker/metrics.test.js
  tools/jil/util/browsers-supported.json
Labels: bug, enhancement, Next Release

#429 Run LT behind a config flag - NR-95944
  src/common/config/state/init.js
  src/features/page_view_timing/instrument/index.js
  tests/functional/pvt/timings.test.js
Labels: safe to test, MMF, Next Release

#428 ALL agents must still send initial connect call - NR-95039
  CHANGELOG.md
  src/common/timing/now.js
  src/common/timing/performance-check.js
  src/common/timing/start-time.js
  src/common/util/submit-data.js
  src/features/page_view_event/aggregate/index.js
  src/features/page_view_event/instrument/index.js
  src/features/utils/lazy-loader.js
  src/loaders/agent.js
  src/loaders/configure/configure.js
  src/loaders/micro-agent.js
  tests/functional/metrics.test.js
  tests/functional/worker/ajax-events.test.js
  tests/functional/worker/all-uncategorized.test.js
  tests/functional/worker/auto-instrumented-errors.test.js
  tests/functional/worker/circular.test.js
  tests/functional/worker/disable-errors.test.js
  tests/functional/worker/dt-headers-fetch.test.js
  tests/functional/worker/eol-harvest.test.js
  tests/functional/worker/errors-harvest-retries.test.js
  tests/functional/worker/errors-have-custom-attributes.test.js
  tests/functional/worker/event-listener-errors.test.js
  tests/functional/worker/external-error.test.js
  tests/functional/worker/metrics.test.js
  tests/functional/worker/notice-error.test.js
  tests/functional/worker/page-action.test.js
  tests/functional/worker/set-error-handler-ignore.test.js
  tests/functional/worker/set-interval-error.test.js
  tests/functional/worker/set-timeout-error.test.js
  tests/functional/worker/xhr-assorted.test.js
  tests/functional/worker/xhr-jserror.test.js
Labels: POC

#430 Add polyfill for Set, now used for desiredFeatures.
  src/cdn/polyfills.js
Labels: safe to test, Next Release

#432 Increase harvest timeout due to race condition.
  tests/functional/worker/xhr-assorted.test.js
Labels: safe to test, Next Release

#431 Fix offset time - NR-96691 - NR-57391
  package-lock.json
  src/common/config/state/runtime.js
  src/common/harvest/harvest-scheduler.js
  src/common/timing/nav-timing.js
  src/common/timing/now.js
  src/common/timing/start-time.js
  src/common/timing/stopwatch.js
  src/common/util/submit-data.js
  src/features/page_view_event/aggregate/index.js
  src/features/page_view_event/instrument/index.js
  src/features/page_view_timing/instrument/index.js
  src/features/session_trace/aggregate/index.js
  tests/browser/nav-cookie.browser.js
  tests/functional/pvt/timings.test.js
  tests/functional/rum/backend-time.test.js
  tests/functional/rum/perf.test.js
  tests/functional/stn/no-negative-timings.test.js
  tests/functional/worker/xhr-assorted.test.js
  tools/jil/util/browsers-supported.json
Labels: bug, safe to test, Next Release

#433 Adding pr comment for asset size report
  .github/workflows/ci.yml
  package-lock.json
  package.json
  tools/jil/util/browsers-supported.json
  tools/scripts/comment-pr.mjs
  tools/scripts/diff-sizes.js
  tools/scripts/diff-sizes.mjs
Labels: maintenance, Next Release

#395 Centralize Stringify method and utilize circular handler
  .husky/pre-commit
  CHANGELOG.md
  VERSION
  package-lock.json
  src/cdn/polyfills.js
  src/common/util/data-size.js
  src/common/util/stringify.js
  src/features/ajax/instrument/distributed-tracing.js
  src/features/jserrors/instrument/index.js
  src/loaders/agent.js
  tests/assets/unhandled-promise-rejection-readable.html
  tests/browser/encode.browser.js
  tests/browser/stringify.browser.js
  tests/functional/err/unhandled-rejection-readable.test.js
Labels: bug, safe to test, maintenance, Next Release

#440 NEWRELIC-7767: Fix diff size percent
  tools/scripts/diff-sizes.mjs
Labels: maintenance, Next Release

#411 Update builds to use SemVer - NEWRELIC-6928 NEWRELIC-6931
  .github/workflows/dev-pr.yml
  .github/workflows/publish-cdn.yml
  .github/workflows/publish-release.yml
  .github/workflows/raise-release-notes-pr.yml
  .husky/pre-commit
  VERSION
  babel-env-vars.js
  babel.npm.cjs.js
  babel.npm.esm.js
  package-lock.json
  package.json
  src/common/config/state/runtime.js
  src/common/constants/environment-variables.js
  tools/jil/util/browsers-supported.json
  tools/scripts/get-build-versions.js
  tools/scripts/sync-version.js
  tools/testing-server/plugins/browserify/browserify-transform.js
  webpack.config.js
Labels: safe to test, MMF, POC, Next Release

#435 Replace CWV metrics with GoogleChrome/web-vitals library NEWRELIC-6214
  src/common/browser-version/ios-version.js
  src/common/cookie/nav-cookie.js
  src/common/metrics/paint-metrics.js
  src/common/timing/now.js
  src/common/timing/stopwatch.js
  src/common/util/user-agent.js
  src/common/window/page-visibility.js
  src/features/page_view_event/aggregate/index.js
  src/features/page_view_event/constants.js
  src/features/page_view_event/instrument/index.js
  src/features/page_view_timing/aggregate/index.js
  src/features/page_view_timing/first-paint.js
  src/features/page_view_timing/instrument/index.js
  src/features/page_view_timing/long-tasks.js
  tests/assets/cls-multiple-big-then-small.html
  tests/assets/cls-multiple-small-then-big.html
  tests/assets/spa/overwrite-add-event-listener.html
  tests/browser/stopwatch.browser.js
  tests/browser/timings-lcp-attributes.browser.js
  tests/browser/timings-lcp-attributes.spec.js
  tests/browser/timings-lcp-cls.browser.js
  tests/browser/timings-lcp-cls.spec.js
  tests/browser/timings-lcp.browser.js
  tests/browser/timings-lcp.spec.js
  tests/functional/pvt/timings.test.js
  tools/jil/util/browser-matcher.js
  tools/jil/util/browsers-supported.json
Labels: safe to test, impact data, large, MMF, Next Release

#442 fix: Minify build correctly
  .editorconfig
  VERSION
  package-lock.json
  tools/jil/util/browsers-supported.json
  tools/scripts/diff-sizes.mjs
  webpack.config.js
Labels: bug, maintenance, Next Release

#446 Edits to change log for v1.229.0
  CHANGELOG.md
Labels: Next Release
