Repository newrelic/newrelic-browser-agent, pull requests merged in 2023-06, with the labels that each got.

#548 chore: sauce connect updates
  .github/workflows/tests.yml
  package-lock.json
  package.json
  tools/browsers-lists/browsers-all.json
  tools/browsers-lists/browsers-supported.json
  tools/browsers-lists/sauce-browsers.mjs
  tools/jil/runner/index.js
  tools/jil/util/external-services.js
  tools/saucelabs/utils.mjs
  tools/test-builds/browser-agent-wrapper/package.json
  tools/test-builds/browser-tests/.npmrc
  tools/test-builds/browser-tests/package-lock.json
  tools/test-builds/browser-tests/package.json
  tools/test-builds/builder.js
  tools/test-builds/raw-src-wrapper/package.json
  tools/test-builds/vite-react-wrapper/package.json
  tools/testing-server/plugins/agent-injector/polyfills-transform.js
  tools/testing-server/plugins/browser-scripts/browser-scripts-transform.js
  tools/wdio/config/sauce.conf.mjs
Labels: small, maintenance

#521 feat: Migrate RUM network call from GET to POST
  .github/actions/find-pull-request/package-lock.json
  src/common/harvest/harvest.js
  src/common/harvest/harvest.test.js
  src/common/url/encode.js
  src/common/util/submit-data.js
  src/features/metrics/aggregate/endpoint-map.js
  src/features/metrics/aggregate/index.js
  src/features/page_view_event/aggregate/index.js
  src/loaders/configure/configure.js
  tests/assets/xhr-add-event-listener-patched.html
  tests/functional/api.test.js
  tests/functional/disable-harvest.test.js
  tests/functional/rum/data.test.js
  tests/functional/rum/no-body.test.js
  tests/functional/spa/basic.test.js
  tests/functional/spa/errors.test.js
  tests/functional/spa/nav-timing.test.js
  tools/jil/driver/TestRun.js
  tools/jil/runner/args.js
  tools/wdio/args.mjs
  tools/wdio/config/sauce.conf.mjs
Labels: safe to test, medium, MMF

#570 feat: remove unused data from stn requests
  package-lock.json
  src/features/session_trace/aggregate/index.js
  tests/functional/stn/index.test.js
  tests/functional/xhr/ajax-events.test.js
  tools/browsers-lists/browsers-supported.json
Labels: safe to test, small, MMF

#577 chore: Remove nav-cookie.test.js functional test
  tests/functional/nav-cookie.test.js
Labels: small

#574 feat: Decorate error objects to facilitate future UI experiences
  package-lock.json
  src/features/jserrors/aggregate/index.js
  src/features/jserrors/instrument/index.js
  tests/assets/duplicate-errors.html
  tests/specs/js-errors/error-payload.e2e.js
Labels: small, MMF

#581 chore: Convert api.test.js from JIL to WDIO - NEWRELIC-9026
  package-lock.json
  tests/assets/api/custom-attribute.html
  tests/functional/api.test.js
  tests/specs/api.e2e.js
  tools/browser-matcher/common-matchers.mjs
Labels: small

#584 chore: Convert err/attributes.test.js from JIL to WDIO - NEWRELIC-9029
  package-lock.json
  package.json
  tests/functional/err/attributes.test.js
  tests/specs/err/attributes.e2e.js
  tools/jil/browser-test.js
  tools/jil/loader/loadBrowser.js
Labels: safe to test, small

#575 chore(main): release 1.235.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#595 chore: Remove eu db actions
  .github/workflows/publish-apm.yml
  .github/workflows/publish-release.yml
  .github/workflows/publish-sudo-polyfills.yml
  package-lock.json
  tools/scripts/check-nrdb.js
  tools/scripts/upload-polyfills-to-nr.js
  tools/scripts/upload-to-nr.js
Labels: maintenance

#600 chore: Change Mootools test to not rely on payloads
  package-lock.json
  tests/assets/third-party-compatibility/mootools/1.6.0-nocompat.html
  tests/specs/third-party-compatibility/mootools.e2e.js
Labels: small, maintenance

#603 fix: Handle chunk load promise error introduced in 1.235.0 - NR-129244
  src/features/session_replay/replay-mode.js
  src/features/utils/instrument-base.js
  src/features/utils/instrument-base.test.js
Labels: bug, safe to test, small

#590 chore(main): release 1.236.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#606 chore: Fix experimental build in staging
  .github/workflows/publish-dev.yml
  package-lock.json
  tools/scripts/upload-ab-to-s3.js
Labels: maintenance
