Repository newrelic/newrelic-browser-agent, pull requests merged in 2023-09, with the labels that each got.

#658 chore(main): release 1.239.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#674 chore(main): release 1.239.1
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#660 chore: Internal entitlements check
  .github/actions/build-ab/index.js
  .github/actions/build-ab/package-lock.json
  .github/actions/build-ab/package.json
  .github/actions/build-ab/template.js
  package-lock.json
Labels: small, maintenance

#635 feat: Centralize web vitals timings
  package-lock.json
  src/common/constants/runtime.js
  src/common/metrics/paint-metrics.js
  src/common/vitals/__mocks__/web-vitals.js
  src/common/vitals/constants.js
  src/common/vitals/cumulative-layout-shift.js
  src/common/vitals/cumulative-layout-shift.test.js
  src/common/vitals/first-contentful-paint.js
  src/common/vitals/first-contentful-paint.test.js
  src/common/vitals/first-input-delay.js
  src/common/vitals/first-input-delay.test.js
  src/common/vitals/first-paint.js
  src/common/vitals/first-paint.test.js
  src/common/vitals/interaction-to-next-paint.js
  src/common/vitals/interaction-to-next-paint.test.js
  src/common/vitals/largest-contentful-paint.js
  src/common/vitals/largest-contentful-paint.test.js
  src/common/vitals/long-task.js
  src/common/vitals/long-task.test.js
  src/common/vitals/time-to-first-byte.js
  src/common/vitals/time-to-first-byte.test.js
  src/common/vitals/vital-metric.js
  src/common/vitals/vital-metric.test.js
  src/features/page_view_event/aggregate/index.js
  src/features/page_view_event/constants.js
  src/features/page_view_event/instrument/index.js
  src/features/page_view_timing/aggregate/index.component-test.js
  src/features/page_view_timing/aggregate/index.js
  src/features/page_view_timing/instrument/index.js
  src/features/page_view_timing/long-tasks.js
  src/features/spa/aggregate/index.js
  tests/browser/timings-fi-attributes.browser.js
  tests/browser/timings-fi-attributes.spec.js
  tests/browser/timings-lcp-cls.browser.js
  tests/browser/timings-lcp-cls.spec.js
  tests/functional/rum/backend-time.test.js
Labels: large

#687 chore: CI - Application version validation
  .github/actions/build-ab/index.js
  .github/actions/build-ab/template.js
  package-lock.json
Labels: maintenance

#691 chore: fix undefined typeerror in ab script
  .github/actions/build-ab/index.js
  package-lock.json
Labels: maintenance

#686 chore: Fix CI - Set app ids to appropriate envs
  .github/workflows/publish-release.yml
  tools/wdio/plugins/testing-server/test-handle-connector.mjs
Labels: maintenance

#688 chore: use experimental loader for experiments
  .github/actions/build-ab/index.js
Labels: maintenance

#678 chore(main): release 1.240.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#705 chore: update settings to match API-E
  .eslintrc.js
  .github/actions/build-ab/template.js
  src/common/config/state/init.js
  src/features/session_replay/aggregate/index.component-test.js
  src/features/session_replay/aggregate/index.js
  tests/assets/rrweb-record.html
  tests/specs/session-replay/helpers.js
  tests/specs/session-replay/mode.e2e.js
  tests/specs/session-replay/rrweb-configuration.e2e.js
  tests/specs/session-replay/session-state.e2e.js
  tests/specs/stn/with-replay-error-mode.e2e.js
  tests/specs/stn/with-session-replay.e2e.js
  tools/testing-server/constants.js
Labels: MMF

#715 chore: Fix workers test job
  .github/workflows/nightly.yml
Labels: maintenance

#711 chore: Keep rrweb on a static version until explicitly upgrading
  package-lock.json
  package.json
Labels: maintenance

#709 chore(main): release 1.241.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#723 chore(main): release 1.242.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#740 fix: Set Session Replay first chunk flags more reliably
  src/common/session/session-entity.component-test.js
  src/common/session/session-entity.js
  src/features/session_replay/aggregate/index.component-test.js
  src/features/session_replay/aggregate/index.js
  tests/specs/session-manager.e2e.js
  tools/wdio/plugins/custom-commands.mjs
Labels: bug, MMF
