Repository newrelic/newrelic-browser-agent, pull requests merged in 2023-02, with the labels that each got.

#378 Implement and verify support for Chrome on iOS (NEWRELIC-6276).
  CHANGELOG.md
  src/common/config/state/runtime.js
  src/common/wrap/wrap-history.js
  src/features/spa/instrument/index.js
  tests/browser/wrap-history.browser.js
  tools/jil/util/browsers-supported.json
Labels: safe to test, Next Release

#388 Format unhandled promise rejection reasons as readable err messages
  src/features/jserrors/instrument/index.js
  tests/assets/unhandled-promise-rejection-readable.html
  tests/functional/err/unhandled-rejection-readable.test.js
Labels: bug, safe to test, Next Release

#386 NEWRELIC-5498: Fixing custom interaction end time
  CHANGELOG.md
  package-lock.json
  package.json
  src/features/spa/aggregate/serializer.js
  tests/assets/spa/multiple-custom-interactions.html
  tests/functional/spa/harvest.test.js
  tools/jil/util/browsers-supported.json
Labels: bug, deploy to dev, smoke test, Next Release

#384 NR-74032: Prevent deny-list ajax time slice metrics
  .github/workflows/tests-polyfill.yml
  CHANGELOG.md
  src/cdn/polyfills.js
  src/features/ajax/aggregate/index.js
  src/features/metrics/instrument/workers-helper.js
  tests/assets/instrumented.html
  tests/functional/stn/ajax-disabled.test.js
  tests/functional/stn/ajax.test.js
  tests/functional/third-party-compatibility/requirejs-compatibility.test.js
  tests/functional/xhr/deny-list.test.js
  tools/testing-server/asset-server.js
  tools/testing-server/router.js
Labels: bug, smoke test, Next Release

#385 Remove references to old build info in readme
  README.md
  tools/jil/util/browsers-supported.json
Labels: maintenance, Next Release

#374 Bind navigator to sendBeacon to prevent illegal invocation errors on …
  CHANGELOG.md
  src/common/util/submit-data.js
Labels: bug, Next Release

#387 Add build version to runtime obj
  CHANGELOG.md
  src/common/config/state/runtime.js
Labels: small, maintenance, Next Release

#383 Raise Docs-Site PR when cutting a new release
  .github/workflows/publish-release.yml
  .github/workflows/raise-release-notes-pr.yml
  .gitignore
  CHANGELOG.md
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  third_party_manifest.json
  tools/scripts/docs-website/create-docs-pr.js
  tools/scripts/docs-website/git-commands.js
  tools/scripts/docs-website/github.js
Labels: maintenance, Next Release, CI-CD

#314 Adding logic for route changes outside a current interaction
  CHANGELOG.md
  src/features/spa/aggregate/index.js
Labels: bug, Next Release

#315 Fix angular lazy routes with api calls (NR-69140, NEWRELIC-4687)
  CHANGELOG.md
  package-lock.json
  src/features/ajax/instrument/index.js
  src/features/spa/aggregate/index.js
  tests/assets/spa/multiple-load.html
  tests/functional/pvt/bfcache.test.js
  tests/functional/spa/fetch.test.js
  tests/functional/spa/multiple-load.test.js
  tools/jil/util/browser-matcher.js
  tools/jil/util/browsers-supported.json
Labels: bug, smoke test, Next Release

#393 Clean up warning messages and test inconsistencies
  .github/workflows/smoke-test.yml
  .github/workflows/tests-polyfill.yml
  src/features/utils/instrument-base.js
  src/loaders/micro-agent.js
Labels: maintenance, Next Release, CI-CD

#396 Remove backticks from transpiled output (NR-86667)
  package-lock.json
  src/common/util/global-scope.js
  third_party_manifest.json
  tools/testing-server/asset-server.js
  webpack.config.js
Labels: Next Release

#397 Run publish current on release
  .github/workflows/publish-release.yml
  THIRD_PARTY_NOTICES.md
  VERSION
  package-lock.json
  third_party_manifest.json
Labels: maintenance, Next Release, CI-CD

#398 NR-86614: Implementing centralized lazy loader
  CHANGELOG.md
  src/features/session_trace/constants.js
  src/features/session_trace/instrument/index.js
  src/features/utils/instrument-base.js
  src/features/utils/lazy-loader.js
  src/loaders/api/api.js
  src/loaders/micro-agent.js
  webpack.config.js
Labels: bug, Next Release

#402 Reverting "scrap old runtime.features from RUM query"
  src/features/page_view_event/aggregate/index.js
  src/features/page_view_event/aggregate/initialized-features.js
Labels: Next Release

#404 Pre release v1225
  CHANGELOG.md
  VERSION
Labels: Next Release

#401 Enabling bfcache
  CHANGELOG.md
  VERSION
  src/common/config/state/init.js
Labels: Next Release

#407 Fix niche getter error in unhandledPromiseRejections - NR-89675
  .eslintrc.js
  CHANGELOG.md
  src/features/jserrors/instrument/index.js
  tests/assets/unhandled-promise-rejection-readable.html
  tests/functional/err/unhandled-rejection-readable.test.js
Labels: bug, Next Release

#405 NR-88545: Disable metrics for missing err entitlement
  .github/workflows/tests.yml
  CHANGELOG.md
  VERSION
  src/common/util/feature-flags.js
  src/features/ajax/aggregate/index.js
  src/features/page_view_timing/aggregate/index.js
  tests/assets/unhandled-promise-rejection-readable.html
  tests/functional/disable-harvest.test.js
Labels: bug, safe to test, small, Next Release

#390 Add general status badge info to readme
  README.md
Labels: maintenance, Next Release

#412 Revert XHR metrics collection - NEWRELIC-6935
  .github/workflows/tests.yml
  CHANGELOG.md
  src/features/ajax/aggregate/index.js
  tests/functional/pvt/bfcache.test.js
  tests/functional/xhr/deny-list.test.js
  tools/jil/util/browser-matcher.js
  tools/testing-server/plugins/agent-injector/polyfills-transform.js
  tools/testing-server/utils/fastify-request.js
Labels: maintenance, Next Release

#371 New INP & long task timings NEWRELIC-2439
  CHANGELOG.md
  THIRD_PARTY_NOTICES.md
  package-lock.json
  package.json
  src/features/page_view_timing/instrument/index.js
  src/features/page_view_timing/instrument/long-tasks.js
  tests/assets/js/some-long-task.js
  tests/assets/long-tasks.html
  tests/functional/pvt/bfcache.test.js
  tests/functional/pvt/timings.test.js
  third_party_manifest.json
  tools/jil/util/browser-matcher.js
Labels: safe to test, MMF, Next Release

#417 [Patch] Remove unwrapping of global api & handlers on abort NEWRELIC-7013
  CHANGELOG.md
  src/common/wrap/index.js
  src/common/wrap/wrap-events.js
  src/common/wrap/wrap-fetch.js
  src/common/wrap/wrap-history.js
  src/common/wrap/wrap-jsonp.js
  src/common/wrap/wrap-mutation.js
  src/common/wrap/wrap-promise.js
  src/common/wrap/wrap-raf.js
  src/common/wrap/wrap-timer.js
  src/common/wrap/wrap-xhr.js
  src/features/ajax/instrument/index.js
  src/features/jserrors/instrument/index.js
  src/features/session_trace/instrument/index.js
  src/features/spa/instrument/index.js
  tests/browser/wrappings/abort-handling.browser.js
  tests/browser/wrappings/wrap-count.browser.js
Labels: bug, Next Release

#420 Adding plugin to generate build stats for upload to cdn
  webpack.config.js
Labels: maintenance, Next Release
