Repository newrelic/newrelic-browser-agent, pull requests merged in 2023-07, with the labels that each got.

#610 fix: Fix potential property of undefined errors
  package-lock.json
  src/common/wrap/wrap-jsonp.js
  src/features/page_view_event/aggregate/initialized-features.js
Labels: bug, safe to test, small

#588 chore: Align SR to new endpoint specifications
  src/common/harvest/harvest.js
  src/common/harvest/harvest.test.js
  src/features/session_replay/aggregate/index.component-test.js
  src/features/session_replay/aggregate/index.js
  src/features/utils/instrument-base.js
  src/features/utils/instrument-base.test.js
  tests/specs/session-replay/harvest.e2e.js
  tests/specs/session-replay/helpers.js
  tests/specs/session-replay/payload.e2e.js
  tests/specs/session-replay/rrweb-configuration.e2e.js
  tests/specs/session-replay/session-pages.e2e.js
  tools/jil/driver/index.js
  tools/testing-server/plugins/bam-parser/index.js
  tools/testing-server/plugins/compression-interceptor/index.js
  tools/testing-server/routes/bam-apis.js
  tools/testing-server/utils/expect-tests.js
  tools/wdio/config/base.conf.mjs
  webpack.config.js
Labels: small, MMF

#613 fix: Defining agent api methods for ts types
  package-lock.json
  src/loaders/agent-base.js
  src/loaders/agent.js
  src/loaders/api/interaction-types.js
  src/loaders/micro-agent.js
  tools/test-builds/vite-react-wrapper/src/newrelic.ts
Labels: bug, small

#609 feat: Stop reporting ajax events going to same beacon
  package-lock.json
  src/common/config/state/init.js
  src/common/config/state/runtime.js
  src/common/deny-list/deny-list.js
  src/common/deny-list/deny-list.test.js
  src/features/ajax/aggregate/index.js
  src/features/session_replay/aggregate/index.component-test.js
  src/loaders/configure/configure.js
  tests/assets/spa/fetch-exceed-max-spa-nodes.html
  tests/browser/xhr/ajax-events.browser.js
  tests/specs/session-replay/harvest.e2e.js
  tests/specs/xhr/deny-list.e2e.js
  tools/testing-server/test-handle.js
  tools/wdio/plugins/testing-server/default-asset-query.mjs
  tools/webpack/loaders/istanbul/index.mjs
Labels: enhancement, needs-follow-up, impact data, small, MMF

#611 chore(main): release 1.237.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending
