Repository newrelic/newrelic-browser-agent, pull requests merged in 2023-05, with the labels that each got.

#499 chore: Enable dot-notation lint rule
  .eslintrc.js
  src/common/event-emitter/contextual-ee.test.js
  src/common/event-emitter/register-handler.test.js
  src/features/page_view_timing/aggregate/index.js
  src/features/spa/aggregate/index.js
  src/loaders/agent.js
  tests/specs/api.e2e.js
  tools/scripts/check-nrdb.js
  tools/scripts/upload-to-nr.js
  tools/wdio/config/sauce.conf.mjs
Labels: safe to test

#515 chore: Update PR template for release please
  .github/pull_request_template.md
Labels: maintenance, Next Release

#516 feat: Allow custom error grouping
  tests/functional/err/custom-handler.test.js
Labels: Next Release

#513 chore: Adjust release automation changes
  tools/scripts/docs-website/create-docs-pr.mjs
Labels: Next Release

#514 chore: Session entity supportability metrics - NEWRELIC-8334
  src/common/config/state/configurable.js
  src/common/session/session-entity.js
  src/common/timer/interaction-timer.js
  src/common/timer/timer.js
  src/common/timer/timer.test.js
  tests/browser/config.browser.js
Labels: safe to test, small, maintenance

#517 chore: Fix basic CI issues before release - NEWRELIC-8375
  .github/workflows/publish-release.yml
  .github/workflows/raise-release-notes-pr.yml
  tools/scripts/check-nrdb.js
  tools/scripts/upload-to-nr.js
Labels: maintenance

#509 chore: Fix experiments CI workflow
  .github/workflows/dev-pr.yml
  .github/workflows/publish-dev.yml
  .github/workflows/publish-experiment.yml
  .github/workflows/tests.yml
  THIRD_PARTY_NOTICES.md
  package-lock.json
  src/features/utils/instrument-base.js
  third_party_manifest.json
  tools/scripts/comment-pr.mjs
  tools/scripts/upload-ab-to-s3.js
  tools/scripts/upload-to-s3.js
  webpack.config.js
Labels: maintenance

#512 chore(main): release 1.232.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#528 chore: Minor CI fixes
  .github/workflows/dev-pr.yml
  .github/workflows/publish-dev.yml
  .github/workflows/publish-experiment.yml
  package-lock.json
  tools/browsers-lists/browsers-all.json
  tools/browsers-lists/browsers-supported.json
Labels: maintenance

#530 chore(main): release 1.232.1
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: safe to test, autorelease: pending

#527 chore: Session trace spring cleaning NEWRELIC-8524
  package-lock.json
  package.json
  src/cdn/polyfills.js
  src/common/window/supports-performance-observer.js
  src/features/session_trace/aggregate/index.js
  src/features/session_trace/constants.js
  src/features/session_trace/instrument/index.js
  src/features/utils/handler-cache.js
  src/features/utils/instrument-base.js
  tests/assets/stn/ensure-passive.html
  tests/functional/stn/ensure-passive-scroll.test.js
  tools/jil/util/browser-matcher.js
Labels: safe to test, small, maintenance

#536 chore: adding wdio workflows
  .github/workflows/nightly.yml
  .github/workflows/wdio-all-browsers.yml
  .github/workflows/wdio-single-browser.yml
  package-lock.json
  package.json
  tests/assets/js/vendor/mootools-1.6.0-more.js
  tests/assets/js/vendor/mootools-1.6.0.js
  tests/assets/requirejs-compatibility.html
  tests/assets/session-entity.html
  tests/assets/spa/jsonp/mootools.html
  tests/assets/third-party-compatibility/jspdf.html
  tests/assets/third-party-compatibility/jspdf/2.5.1.html
  tests/assets/third-party-compatibility/mootools/1.6.0-nocompat.html
  tests/assets/third-party-compatibility/requirejs/2.3.6.html
  tests/functional/spa/jsonp.test.js
  tests/functional/third-party-compatibility/jspdf.test.js
  tests/functional/third-party-compatibility/requirejs-compatibility.test.js
  tests/specs/api.e2e.js
  tests/specs/session-manager.e2e.js
  tests/specs/stack-trace.e2e.js
  tests/specs/third-party-compatibility/jspdf.e2e.js
  tests/specs/third-party-compatibility/mootools.e2e.js
  tests/specs/third-party-compatibility/requirejs.e2e.js
  tests/specs/third-party-compatibility/run-test.js
  tests/util/defaults.js
  tools/browser-matcher/common-matchers.mjs
  tools/browser-matcher/matcher-rule.mjs
  tools/browser-matcher/spec-matcher.mjs
  tools/browsers-lists/browsers-list.mjs
  tools/browsers-lists/utils.mjs
  tools/test-builds/browser-agent-wrapper/package.json
  tools/test-builds/raw-src-wrapper/package.json
  tools/test-builds/vite-react-wrapper/package.json
  tools/testing-server/index.js
  tools/testing-server/plugins/agent-injector/debug-shim.js
  tools/testing-server/plugins/test-handle/index.js
  tools/testing-server/test-handle.js
  tools/wdio/args.mjs
  tools/wdio/bin/server.js
  tools/wdio/config/base.conf.mjs
  tools/wdio/config/sauce.conf.mjs
  tools/wdio/config/selenium.conf.mjs
  tools/wdio/config/specs.conf.mjs
  tools/wdio/plugins/browser-matcher.mjs
  tools/wdio/plugins/custom-commands.mjs
  tools/wdio/plugins/jil-commands.mjs
  tools/wdio/plugins/mocha-globals/globals.mjs
  tools/wdio/plugins/mocha-globals/index.mjs
  tools/wdio/plugins/newrelic-reporter.mjs
  tools/wdio/plugins/testing-server/default-asset-query.mjs
  tools/wdio/plugins/testing-server/index.mjs
  tools/wdio/plugins/testing-server/launcher.mjs
  tools/wdio/plugins/testing-server/test-handle-connector.mjs
  tools/wdio/runner.mjs
Labels: safe to test, small, maintenance, Next Release

#539 feat: Capture metrics for usage of MooTools and certain polyfills
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/common/metrics/framework-detection.js
  src/common/url/protocol.test.js
  src/features/metrics/aggregate/framework-detection.js
  src/features/metrics/aggregate/framework-detection.test.js
  src/features/metrics/aggregate/index.js
  src/features/metrics/aggregate/polyfill-detection.es5.js
  src/features/metrics/aggregate/polyfill-detection.es5.test.js
  src/features/metrics/aggregate/polyfill-detection.js
  src/features/metrics/aggregate/polyfill-detection.test.js
  tests/assets/polyfill-metrics.html
  tests/functional/metrics.test.js
  tests/specs/api.e2e.js
  tests/specs/metrics.e2e.js
  tests/specs/session-manager.e2e.js
  tests/specs/stack-trace.e2e.js
  tests/specs/third-party-compatibility/run-test.js
  tests/worker/metrics.test.js
  tools/jest-matchers/index.mjs
  tools/wdio/config/specs.conf.mjs
  tools/wdio/plugins/browser-matcher.mjs
  tools/wdio/plugins/custom-commands.mjs
  tools/wdio/plugins/mocha-globals/globals.mjs
  tools/wdio/plugins/testing-server/default-asset-query.mjs
Labels: Next Release

#544 fix: Refactor usage of Array.from to address MooTools conflict
  babel.config.js
  jest.config.js
  src/cdn/polyfills.js
  src/common/drain/drain.js
  src/common/wrap/wrap-fetch.js
  src/common/wrap/wrap-function.js
  src/common/wrap/wrap-promise.js
  src/loaders/agent.js
Labels: safe to test

#546 fix: Address "configurable" warnings arising from user-agent module
  src/common/config/state/runtime.js
  src/common/util/user-agent.js
Labels: bug, safe to test, Next Release

#543 chore: Check configuration when importing Aggregators
  package.json
  src/features/ajax/aggregate/index.js
  src/features/jserrors/aggregate/index.js
  src/features/metrics/aggregate/index.js
  src/features/page_action/aggregate/index.js
  src/features/page_view_event/aggregate/index.js
  src/features/page_view_timing/aggregate/index.js
  src/features/session_trace/aggregate/index.js
  src/features/spa/aggregate/index.js
  src/features/utils/aggregate-base.js
  src/features/utils/feature-base.js
  src/loaders/configure/configure.js
Labels: safe to test, small, Next Release

#540 chore(main): release 1.233.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: safe to test, autorelease: pending

#549 chore: Experimental builds for local testing
  src/cdn/experimental.js
  webpack.config.js
Labels: small, maintenance, MMF

#541 chore: Add route and compression handling to test-server
  .github/workflows/selenium-test.yml
  package.json
  src/common/config/state/init.js
  src/common/harvest/harvest-scheduler.js
  src/common/harvest/harvest.js
  src/features/session_replay/aggregate/index.js
  tests/assets/rrweb-record.html
  tests/functional/api.test.js
  tests/functional/xhr/harvest.test.js
  tools/testing-server/index.js
  tools/testing-server/plugins/compression-interceptor/index.js
  tools/testing-server/routes/bam-apis.js
  tools/testing-server/routes/mock-apis.js
  tools/testing-server/routes/tests-index.js
  tools/testing-server/utils/fastify-request.js
Labels: safe to test, small, MMF

#561 fix: Address early return preempting XHR harvest re-schedule
  src/common/harvest/harvest-scheduler.js
  src/common/harvest/harvest-scheduler.test.js
Labels: bug, safe to test, small, Next Release

#562 chore(main): release 1.233.1
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending
