Repository newrelic/newrelic-browser-agent, pull requests merged in 2023-04, with the labels that each got.

#438 Handle sendBeacon more gracefully - NR-95365
  src/common/util/submit-data.js
Labels: bug, Next Release

#449 chore: swapping out array reduce impl
  src/common/util/reduce.js
  src/features/jserrors/aggregate/compute-stack-trace.js
  src/features/session_trace/aggregate/index.js
  tests/browser/reduce.browser.js
Labels: safe to test, small, standalone, Next Release

#450 Fix Docs Site PR CI - NR-103815
  .github/workflows/publish-release.yml
  tools/scripts/docs-website/create-docs-pr.js
  tools/scripts/docs-website/git-commands.js
Labels: Next Release

#456 feat: type declarations for typescript projects
  CHANGELOG.md
  package-lock.json
  package.json
  src/common/wrap/wrap-events.js
  src/common/wrap/wrap-fetch.js
  src/common/wrap/wrap-function.js
  src/common/wrap/wrap-history.js
  src/common/wrap/wrap-jsonp.js
  src/common/wrap/wrap-raf.js
  src/common/wrap/wrap-timer.js
  src/common/wrap/wrap-xhr.js
  src/index.js
  tests/functional/npm/basic.test.js
  tools/test-builds/browser-agent-wrapper/webpack.config.js
  tools/test-builds/vite-react-wrapper/.npmrc
  tools/test-builds/vite-react-wrapper/index.html
  tools/test-builds/vite-react-wrapper/package.json
  tools/test-builds/vite-react-wrapper/src/App.tsx
  tools/test-builds/vite-react-wrapper/src/main.tsx
  tools/test-builds/vite-react-wrapper/src/newrelic.ts
  tools/test-builds/vite-react-wrapper/tsconfig.json
  tools/test-builds/vite-react-wrapper/tsconfig.node.json
  tools/test-builds/vite-react-wrapper/vite.config.ts
  tsconfig.json
  types.ts
Labels: small, standalone, Next Release

#459 SMs - SessionTrace duration and endpoint payload sizes per page
  .husky/pre-commit
  src/common/config/state/runtime.js
  src/common/harvest/harvest.js
  src/features/metrics/aggregate/index.js
  src/features/page_view_event/aggregate/index.js
  tools/jil/util/browsers-supported.json
Labels: Next Release

#452 chore: add jest tests for mapOwn
  src/common/util/map-own.js
  src/common/util/map-own.test.js
  tests/browser/map-own.browser.js
Labels: safe to test, small, standalone, Next Release

#457 Capture supportability metrics for console methods (NEWRELIC-7770)
  .husky/pre-commit
  package-lock.json
  src/common/wrap/index.js
  src/common/wrap/wrap-console.js
  src/common/wrap/wrap-function.js
  src/features/metrics/instrument/index.js
  tests/assets/console-methods.html
  tests/functional/metrics.test.js
  tools/jil/util/browsers-supported.json
  tools/testing-server/plugins/browserify/browserify-transform.js
Labels: Next Release

#437 Run a basic test against <all> browsers - NEWRELIC-7583
  .github/workflows/tests-all.yml
  .husky/pre-commit
  tests/assets/graceful-error.html
  tests/functional/graceful-error.test.js
  tools/jil/runner/args.js
  tools/jil/util/browser-list.js
  tools/jil/util/browsers-all.json
  tools/jil/util/sauce-browsers.js
Labels: Next Release

#443 Add standard setUserId & expand setErrorHandler|setCustomAttribute APIs
  .eslintrc.js
  CHANGELOG.md
  package-lock.json
  package.json
  src/common/util/console.js
  src/common/window/session-storage.js
  src/common/window/top-level-callers.js
  src/features/jserrors/aggregate/index.js
  src/features/jserrors/instrument/index.js
  src/loaders/api/api.js
  src/loaders/api/apiAsync.js
  src/loaders/configure/configure.js
  tests/assets/api/customMetrics.html
  tests/browser/spa/api.browser.js
  tests/functional/api.test.js
  tests/functional/err/assertion-helpers.js
  tests/functional/err/custom-handler.test.js
  tests/functional/err/ignore-error.test.js
  tests/functional/uncat-internal-help.cjs
  tests/functional/worker/metrics.test.js
  tools/testing-server/plugins/agent-injector/script-transform.js
  tools/testing-server/plugins/browserify/browserify-transform.js
Labels: small, MMF, Next Release

#458 chore: unit tests for url utilities
  src/common/url/clean-url.test.js
  src/common/url/encode.test.js
  src/common/url/location.js
  src/common/url/location.test.js
  src/common/url/parse-url.test.js
  src/common/url/protocol.js
  src/common/url/protocol.test.js
  src/common/util/obfuscate.js
  src/features/metrics/aggregate/index.js
  tests/browser/clean-url.browser.js
  tests/browser/encode.browser.js
  tests/browser/xhr/parse-url.browser.js
Labels: small, maintenance

#461 Fix typo in release action - NEWRELIC-7894
  .github/workflows/publish-release.yml
  tools/scripts/docs-website/create-docs-pr.js
Labels: bug, Next Release

#462 fix: build time env variables
  .eslintrc.js
  THIRD_PARTY_NOTICES.md
  babel-env-vars.js
  babel.config.js
  babel.npm.cjs.js
  babel.npm.esm.js
  package-lock.json
  package.json
  src/common/config/state/runtime.js
  src/common/constants/env.cdn.js
  src/common/constants/env.js
  src/common/constants/env.npm.js
  src/common/constants/environment-variables.js
  src/common/harvest/harvest.js
  src/features/metrics/aggregate/index.js
  tests/browser/harvest.browser.js
  tests/browser/protocol.browser.js
  tests/browser/protocol.spec.js
  tests/functional/npm/basic.test.js
  third_party_manifest.json
  tools/jil/util/browsers-all.json
  tools/jil/util/browsers-supported.json
  tools/scripts/babel-plugin-transform-import.js
  tools/testing-server/plugins/browserify/browserify-transform.js
  webpack.config.js
Labels: small, standalone, Next Release

#468 chore: jest tests for event-emitter
  package-lock.json
  src/common/event-emitter/contextual-ee.test.js
  src/common/event-emitter/handle.test.js
  src/common/event-emitter/register-handler.test.js
  tests/browser/contextual-ee.browser.js
  tests/browser/handle.browser.js
  tools/jil/util/browsers-all.json
  tools/jil/util/browsers-supported.json
Labels: small, maintenance, Next Release

#466 chore: jests tests for id generators
  src/common/ids/id.js
  src/common/ids/id.test.js
  src/common/ids/unique-id.js
  src/common/ids/unique-id.test.js
  tests/browser/id.browser.js
  tests/browser/unique-id.browser.js
Labels: small, maintenance, Next Release

#477 fix: promise wrapper race/all
  src/common/wrap/wrap-promise.js
  src/common/wrap/wrap-promise.test.js
  tests/browser/third-party-compatibility/jspdf.browser.js
Labels: bug, small, Next Release

#476 Console observability performance tests (NR-108961)
  package-lock.json
  package.json
  tests/assets/console-methods.html
  tests/specs/console-performance.e2e.js
  tools/wdio/config/sauce.conf.mjs
  tools/wdio/plugins/testing-server/test-handle-connector.mjs
  tools/wdio/util/browser-list.mjs
Labels: small, maintenance, Next Release

#473 Upload "fuzzy" versions to NRDB - NEWRELIC-7720
  package-lock.json
  package.json
  tools/scripts/clone.js
  tools/scripts/upload-to-nr.js
Labels: impact data, small, MMF

#486 fix: cwv add error prevention logic
  src/features/page_view_timing/aggregate/index.js
Labels: bug, small, Next Release

#479 patch: Omit CLS of 0s if not reported by web-vitals
  CHANGELOG.md
  src/common/window/page-visibility.js
  src/features/page_view_timing/aggregate/index.js
  tests/assets/cls-interaction.html
  tests/assets/cls-load.html
  tests/assets/pagehide.html
  tests/functional/pvt/timings.test.js
Labels: bug, small, Next Release

#489 Add fallbacks for performance timings
  src/common/timing/nav-timing.js
  src/common/timing/nav-timing.test.js
  src/features/page_view_event/aggregate/index.js
  src/features/session_trace/aggregate/index.js
Labels: safe to test, Next Release
