Repository newrelic/newrelic-browser-agent, pull requests merged in 2024-10, with the labels that each got.

#1195 feat: Aggregate UserActions
  src/common/dom/iframe.js
  src/common/dom/selector-path.js
  src/features/generic_events/aggregate/index.js
  src/features/generic_events/aggregate/user-actions/aggregated-user-action.js
  src/features/generic_events/aggregate/user-actions/user-actions-aggregator.js
  src/features/generic_events/constants.js
  src/features/metrics/aggregate/index.js
  tests/assets/user-actions.html
  tests/components/generic_events/aggregate/index.test.js
  tests/specs/ins/harvesting.e2e.js
  tests/unit/common/dom/selector-path.test.js
  tests/unit/features/generic_events/aggregate/user-actions/aggregated-user-action.test.js
  tests/unit/features/generic_events/aggregate/user-actions/user-actions-aggregator.test.js
  tools/testing-server/constants.js
Labels: Innovation

#1220 feat: Move deregisterDrain method to feature-base
  src/features/generic_events/aggregate/index.js
  src/features/generic_events/instrument/index.js
  src/features/jserrors/aggregate/index.js
  src/features/metrics/aggregate/index.js
  src/features/session_replay/aggregate/index.js
  src/features/session_trace/aggregate/index.js
  src/features/session_trace/instrument/index.js
  src/features/soft_navigations/aggregate/index.js
  src/features/spa/aggregate/index.js
  src/features/utils/aggregate-base.js
  src/features/utils/feature-base.js
Labels: safe to test

#1222 chore(main): release 1.270.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#1228 chore(main): release 1.270.1
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#1230 chore(main): release 1.270.2
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#1236 chore(main): release 1.270.3
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending
