Repository newrelic/newrelic-browser-agent, pull requests merged in 2025-02, with the labels that each got.

#1370 chore: add browser pressure poc to postamble script
  .github/actions/build-ab/templates/postamble.js
Labels: Innovation

#1344 chore: Support experiment uploads without deploy to internal site
  .github/workflows/branch-cleanup.yml
  .github/workflows/publish-experiment.yml
Labels: Blocked

#1378 chore(main): release 1.282.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#1385 chore(main): release 1.283.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#1389 chore(main): release 1.283.1
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#1393 chore(main): release 1.283.2
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending
