Repository newrelic/newrelic-browser-agent, pull requests merged in 2025-03, with the labels that each got.

#1396 fix: Guard against non-CSSStyleSheet when fixing sheets for replay
  src/features/session_replay/shared/stylesheet-evaluator.js
  tests/unit/features/session_replay/shared/stylesheet-evaluator.test.js
Labels: Waiting For Freeze

#1383 fix: Upgrade rrweb to 18
  package-lock.json
  package.json
Labels: has dependency, Waiting For Freeze

#1411 chore(main): release 1.284.1
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending

#1415 chore(main): release 1.285.0
  CHANGELOG.md
  changelog.json
  package-lock.json
  package.json
Labels: autorelease: pending
